version: '3.5'
services:
  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysql_exporter
    restart: always
    ports:
      - 9104:9104
    command:
     - --mysqld.username=dbuser:dbpassword
     - --mysqld.address=dbhost:3306
    networks:
      - prometheus

networks:
  prometheus:
    name: prometheus
    external: true
