version: '3.8'
services:
  prometheus:
    image: artifactory.asredanesh.com/docker/prometheus:v1
    container_name: prometheus
    ports:
      - 9090:9090
    restart: always
    networks:
      - prometheus
      - haproxy
      - zbx
            

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    #volumes:
    #  - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9100:9100
    restart: always
    networks:
      - prometheus
      - haproxy
      - zbx
      
  alertmanager:
    image: quay.io/prometheus/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
      #- ./prometheus/rules.yml:/etc/prometheus/rules.yml
    ports:
      - 9093:9093
    restart: always
    networks:
      - prometheus
      - haproxy
      - zbx
      
  grafana:
    image: artifactory.asredanesh.com/docker/grafana:7.5.6-ubuntu
    container_name: grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/plugins/:/var/lib/grafana/plugins/
    ports:
      - 3000:3000
 #   environment:
#      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      #- GF_SECURITY_ADMIN_USER=admin
      #- GF_SECURITY_ADMIN_PASSWORD=password
    restart: always
    networks:
      - prometheus
      - haproxy
      - zbx
            
  cadvisor:
    image: artifactory.asredanesh.com/docker/gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
    #  - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - prometheus
      - haproxy
      - zbx
      
networks:
  prometheus:
    name: prometheus
    external: true
  haproxy:
    name: haproxy
    external: true
  zbx:
    name: zbx
    external: true
